nelmio_api_doc:
    documentation:
        info:
            title: SPINpay
            description:
            version: 0.0.1
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
        paths:
            ### LOGIN ###
            /token/login:
                post:
                    tags:
                        - Authentication
                    description: Login into the api.
                    produces:
                        - application/json
                    parameters:
                        - name: Login
                          description: AppUser to login
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  email:
                                      type: string
                                  password:
                                      type: string
                    responses:
                        '200':
                            description: Login successful
                            schema:
                                type: object
                                properties:
                                    token:
                                        type: string
                                    refresh_token:
                                        type: string
            ### REFRESH TOKEN ###
            /token/refresh:
                post:
                    tags:
                        - Authentication
                    description: Refresh the authentication token.
                    produces:
                        - application/json
                    parameters:
                        - name: Refresh
                          description: Refresh token.
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  refresh_token:
                                      type: string
                    responses:
                        '200':
                            description: Login successful
                            schema:
                                type: object
                                properties:
                                    token:
                                        type: string
                                    refresh_token:
                                        type: string
    areas:
        default:
            path_patterns: [ '^/api', '^/user' ]


