#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /token/login

gesdinet_jwt_refresh_token:
  path:       /token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

app.swagger_ui:
  path: /
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
